use std::collections::{HashMap, HashSet};
use crate::disassembler::{Instruction, Value};
use crate::disassembler::opcodes::Op;
use super::cfg::PayloadCfg;

pub struct ProbeResult {
    pub slot: usize,
    pub func_addr: usize,
    pub name: String,
    pub chain: Vec<String>,
}

pub struct NameMap {
    pub obf_to_name: HashMap<String, String>,
    pub name_to_obf: HashMap<String, String>,
    pub sub_props: HashMap<String, HashMap<String, String>>,
}


pub struct FingerprintResult {
    pub probes: Vec<ProbeResult>,
    pub names: NameMap,
}

enum FpMatch {
    Token(&'static str),
    TokenAll(&'static [&'static str]),
    Freq(&'static [(&'static str, usize)]),
    FreqMax(&'static [(&'static str, usize)], usize),
    FreqDeep(&'static [(&'static str, usize)]),
}

struct FpDef {
    name: &'static str,
    matcher: FpMatch,
    sub_props: bool,
    sub_prop_names: &'static [&'static str],
}

const FP_DEFS: &[FpDef] = &[
    FpDef { name: "screen_orientation", matcher: FpMatch::Token("mozOrientation"), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "pad_start", matcher: FpMatch::Freq(&[("Math", 1), ("floor", 1), ("length", 3), ("String", 3), (" ", 1), ("slice", 1), ("", 1)]), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "try_run", matcher: FpMatch::Freq(&[("not supported", 1)]), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "safe_get", matcher: FpMatch::Freq(&[("object", 1)]), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "srcdoc_descriptor", matcher: FpMatch::FreqDeep(&[("getOwnPropertyDescriptor", 2), ("srcdoc", 2), ("toString", 2), ("get", 1), ("set", 1), ("Object", 2), ("", 1)]), sub_props: true, sub_prop_names: &["srcdoc_getter", "srcdoc_setter"] },
    FpDef { name: "fake_error_name", matcher: FpMatch::Freq(&[("Error", 2), ("toString", 1), ("replace", 1), ("g", 1)]), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "hardware_concurrency", matcher: FpMatch::FreqMax(&[("hardwareConcurrency", 1)], 6), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "webgl2_get_param", matcher: FpMatch::Freq(&[("WebGL2RenderingContext", 1), ("prototype", 1), ("getParameter", 1)]), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "webgl1_get_param", matcher: FpMatch::Freq(&[("WebGLRenderingContext", 1), ("prototype", 1), ("getParameter", 1)]), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "plugins_list", matcher: FpMatch::FreqDeep(&[("navigator", 1), ("plugins", 1), ("suffixes", 1), ("type", 1), ("description", 1), ("map", 2), ("from", 2)]), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "timezone_string", matcher: FpMatch::Freq(&[("Date", 1), ("toString", 1), ("match", 1), ("\\((.+)\\)", 1), ("", 1), ("N/A", 2)]), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "prop_recorder", matcher: FpMatch::FreqDeep(&[("Proxy", 2), ("get", 1), ("concat", 4), (":", 1), ("Array", 1), ("apply", 1), ("String", 1)]), sub_props: false, sub_prop_names: &[] },
    FpDef { name: "animation_timing", matcher: FpMatch::Token("getComputedTiming"), sub_props: true, sub_prop_names: &[] },
    FpDef { name: "audio_context", matcher: FpMatch::Token("AudioContext"), sub_props: true, sub_prop_names: &[] },
    FpDef { name: "input_dimensions", matcher: FpMatch::Token("checkbox"), sub_props: true, sub_prop_names: &["input_color", "input_checkbox", "input_range", "input_file", "input_time", "input_submit", "input_reset", "input_search", "input_password", "input_tel"] },
    FpDef { name: "emoji_rendering", matcher: FpMatch::Token("⚪"), sub_props: true, sub_prop_names: &["emoji_‼", "emoji_〰", "emoji_⬅", "emoji_⬆", "emoji_⚪"] },
    FpDef { name: "timer_ids", matcher: FpMatch::FreqMax(&[("setInterval", 2), ("setTimeout", 2), ("", 4)], 10), sub_props: true, sub_prop_names: &["setInterval_id", "setTimeout_id"] },
    FpDef { name: "webgl_context", matcher: FpMatch::TokenAll(&["WEBGL_debug_renderer_info", "canvas", "moz-webgl"]), sub_props: true, sub_prop_names: &["gl_context", "gl_debug_info"] },
    FpDef { name: "navigator_info", matcher: FpMatch::Token("MimeTypeArray"), sub_props: true, sub_prop_names: &["mime_count", "nav_language", "lang_count", "no_chrome", "plugin_proto", "mime_proto", "conn_rtt"] },
];

struct ProbeDef {
    name: &'static str,
    matcher: FpMatch,
    int_val: Option<i32>,
}

const PROBE_DEFS: &[ProbeDef] = &[
    ProbeDef { name: "crypto_random_avg", matcher: FpMatch::Freq(&[("crypto", 1), ("getRandomValues", 1), ("Uint16Array", 1), ("Math", 1), ("floor", 1)]), int_val: None },
    ProbeDef { name: "audio_wav", matcher: FpMatch::Token("audio/wav;"), int_val: None },
    ProbeDef { name: "video_mp4_mp4a", matcher: FpMatch::Token("video/mp4; codecs=mp4a.40.2"), int_val: None },
    ProbeDef { name: "iterator_stop", matcher: FpMatch::TokenAll(&["s", "stop"]), int_val: None },
    ProbeDef { name: "user_activation_is_active", matcher: FpMatch::TokenAll(&["userActivation", "isActive"]), int_val: None },
    ProbeDef { name: "prop_recorder_own_descriptors", matcher: FpMatch::TokenAll(&["getOwnPropertyDescriptors", "join"]), int_val: None },
    ProbeDef { name: "touch_event_check", matcher: FpMatch::Token("TouchEvent"), int_val: None },
    ProbeDef { name: "system_colors", matcher: FpMatch::Token("ActiveBorder"), int_val: None },
    ProbeDef { name: "navigator_fake_rml", matcher: FpMatch::TokenAll(&["navigator", "rml"]), int_val: None },
    ProbeDef { name: "navigator_fake_rnd", matcher: FpMatch::TokenAll(&["navigator", "rnd"]), int_val: None },
    ProbeDef { name: "navigator_fake_v", matcher: FpMatch::FreqMax(&[("navigator", 1), ("v", 1)], 4), int_val: None },
    ProbeDef { name: "video_matroska_theora", matcher: FpMatch::Token("video/x-matroska; codecs=\"theora, vorbis\""), int_val: None },
    ProbeDef { name: "aspect_ratio", matcher: FpMatch::Token("aspect-ratio"), int_val: None },
    ProbeDef { name: "css_column", matcher: FpMatch::TokenAll(&["s", "column"]), int_val: None },
    ProbeDef { name: "video_ogg_speex", matcher: FpMatch::Token("video/ogg; codecs=speex"), int_val: None },
    ProbeDef { name: "audio_wav_codec0", matcher: FpMatch::Token("audio/wav; codecs=\"0\""), int_val: None },
    ProbeDef { name: "navigator_mime_types", matcher: FpMatch::Token("navigator.mimeTypes"), int_val: None },
    ProbeDef { name: "color_gamut", matcher: FpMatch::Token("color-gamut"), int_val: None },
    ProbeDef { name: "crypto_random_raw", matcher: FpMatch::Freq(&[("crypto", 1), ("getRandomValues", 1), ("Uint16Array", 1)]), int_val: None },
    ProbeDef { name: "css_counter", matcher: FpMatch::TokenAll(&["s", "counter"]), int_val: None },
    ProbeDef { name: "css_scroll", matcher: FpMatch::TokenAll(&["s", "scroll"]), int_val: None },
    ProbeDef { name: "audio_webm", matcher: FpMatch::Token("audio/webm;"), int_val: None },
    ProbeDef { name: "window_location_origin", matcher: FpMatch::FreqMax(&[("location", 1), ("origin", 1)], 3), int_val: None },
    ProbeDef { name: "reflect_own_keys", matcher: FpMatch::TokenAll(&["Reflect", "ownKeys"]), int_val: None },
    ProbeDef { name: "window_crypto", matcher: FpMatch::FreqDeep(&[("crypto", 1)]), int_val: None },
    ProbeDef { name: "audio_wave_codec0", matcher: FpMatch::Token("audio/wave; codecs=0"), int_val: None },
    ProbeDef { name: "audio_wave", matcher: FpMatch::Token("audio/wave;"), int_val: None },
    ProbeDef { name: "css_outline", matcher: FpMatch::TokenAll(&["s", "outline"]), int_val: None },
    ProbeDef { name: "css_object", matcher: FpMatch::TokenAll(&["s", "object"]), int_val: None },
    ProbeDef { name: "audio_wav_codec2", matcher: FpMatch::Token("audio/wav; codecs=\"2\""), int_val: None },
    ProbeDef { name: "prop_recorder_function", matcher: FpMatch::TokenAll(&["Function", ""]), int_val: None },
    ProbeDef { name: "css_color", matcher: FpMatch::TokenAll(&["s", "color"]), int_val: None },
    ProbeDef { name: "pointer", matcher: FpMatch::Token("pointer"), int_val: None },
    ProbeDef { name: "css_overflow", matcher: FpMatch::TokenAll(&["s", "overflow"]), int_val: None },
    ProbeDef { name: "gl_max_combined_uniform_blocks", matcher: FpMatch::Token("MAX_COMBINED_UNIFORM_BLOCKS"), int_val: None },
    ProbeDef { name: "css_get", matcher: FpMatch::TokenAll(&["s", "get"]), int_val: None },
    ProbeDef { name: "css_webkit", matcher: FpMatch::TokenAll(&["s", "webkit"]), int_val: None },
    ProbeDef { name: "dynamic_range", matcher: FpMatch::Token("dynamic-range"), int_val: None },
    ProbeDef { name: "math_random_sum_6", matcher: FpMatch::Freq(&[("random", 1), ("bind", 1), ("floor", 1), ("Math", 3)]), int_val: Some(6) },
    ProbeDef { name: "math_random_sum", matcher: FpMatch::Freq(&[("random", 1), ("bind", 1), ("floor", 1), ("Math", 3)]), int_val: None },
    ProbeDef { name: "video_mpeg", matcher: FpMatch::Token("video/mpeg;"), int_val: None },
    ProbeDef { name: "intl_collator", matcher: FpMatch::Token("collation"), int_val: None },
    ProbeDef { name: "overflow_block", matcher: FpMatch::Token("optional-paged"), int_val: None },
    ProbeDef { name: "css_grid", matcher: FpMatch::TokenAll(&["s", "grid"]), int_val: None },
    ProbeDef { name: "script_transfer_rate", matcher: FpMatch::TokenAll(&["resource", "transferSize", "duration"]), int_val: None },
    ProbeDef { name: "prop_recorder_keys", matcher: FpMatch::TokenAll(&["keys", "join"]), int_val: None },
    ProbeDef { name: "prop_recorder_request", matcher: FpMatch::TokenAll(&["Request", "ftp:"]), int_val: None },
    ProbeDef { name: "prop_recorder_array", matcher: FpMatch::TokenAll(&["Array", "join"]), int_val: None },
    ProbeDef { name: "hover", matcher: FpMatch::FreqMax(&[("hover", 2), ("none", 1)], 4), int_val: None },
    ProbeDef { name: "device_width", matcher: FpMatch::Token("device-width"), int_val: None },
    ProbeDef { name: "css_clip", matcher: FpMatch::TokenAll(&["s", "clip"]), int_val: None },
    ProbeDef { name: "gl_version", matcher: FpMatch::Token("VERSION"), int_val: None },
    ProbeDef { name: "patched_func_string_err_msg", matcher: FpMatch::Token("patchedFuncStringErrMsg"), int_val: None },
    ProbeDef { name: "prop_recorder_own_property_names", matcher: FpMatch::TokenAll(&["getOwnPropertyNames", "join"]), int_val: None },
    ProbeDef { name: "css_mask", matcher: FpMatch::TokenAll(&["s", "mask"]), int_val: None },
    ProbeDef { name: "video_mp4_mp4v", matcher: FpMatch::Token("video/mp4; codecs=\"mp4v.20.240, mp4a.40.2\""), int_val: None },
    ProbeDef { name: "prop_recorder_assign", matcher: FpMatch::TokenAll(&["assign", "join"]), int_val: None },
    ProbeDef { name: "window_performance", matcher: FpMatch::FreqDeep(&[("performance", 1)]), int_val: None },
    ProbeDef { name: "css_word", matcher: FpMatch::TokenAll(&["s", "word"]), int_val: None },
    ProbeDef { name: "css_moz", matcher: FpMatch::TokenAll(&["s", "moz"]), int_val: None },
    ProbeDef { name: "media_color", matcher: FpMatch::FreqMax(&[("color", 1)], 3), int_val: None },
    ProbeDef { name: "css_min", matcher: FpMatch::TokenAll(&["s", "min"]), int_val: None },
    ProbeDef { name: "audio_x_mpegurl", matcher: FpMatch::Token("audio/x-mpegurl"), int_val: None },
    ProbeDef { name: "device_posture", matcher: FpMatch::Token("device-posture"), int_val: None },
    ProbeDef { name: "css_border", matcher: FpMatch::TokenAll(&["s", "border"]), int_val: None },
    ProbeDef { name: "any_pointer", matcher: FpMatch::Token("any-pointer"), int_val: None },
    ProbeDef { name: "prop_recorder_array_buffer", matcher: FpMatch::TokenAll(&["ArrayBuffer", "join"]), int_val: None },
    ProbeDef { name: "prefers_color_scheme", matcher: FpMatch::Token("prefers-color-scheme"), int_val: None },
    ProbeDef { name: "gl_max_uniform_buffer_bindings", matcher: FpMatch::Token("MAX_UNIFORM_BUFFER_BINDINGS"), int_val: None },
    ProbeDef { name: "prop_recorder_to_string", matcher: FpMatch::FreqMax(&[("toString", 1), ("join", 1), (",", 1)], 6), int_val: None },
    ProbeDef { name: "date_fingerprint", matcher: FpMatch::FreqMax(&[("Date", 1), ("now", 1)], 6), int_val: Some(86400000) },
    ProbeDef { name: "hourly_fingerprint", matcher: FpMatch::FreqMax(&[("Date", 1), ("now", 1)], 6), int_val: Some(3600000) },
    ProbeDef { name: "intl_plural_rules", matcher: FpMatch::Token("cardinal"), int_val: None },
    ProbeDef { name: "audio_x_mpeg", matcher: FpMatch::Token("audio/x-mpeg"), int_val: None },
    ProbeDef { name: "css_padding", matcher: FpMatch::TokenAll(&["s", "padding"]), int_val: None },
    ProbeDef { name: "color_index", matcher: FpMatch::Token("color-index"), int_val: None },
    ProbeDef { name: "math_random_pow", matcher: FpMatch::TokenAll(&["random", "pow"]), int_val: None },
    ProbeDef { name: "css_epub", matcher: FpMatch::TokenAll(&["s", "epub"]), int_val: None },
    ProbeDef { name: "navigator_fake_date_time_string", matcher: FpMatch::TokenAll(&["navigator", "dateTimeString"]), int_val: None },
    ProbeDef { name: "css_stroke", matcher: FpMatch::TokenAll(&["s", "stroke"]), int_val: None },
    ProbeDef { name: "prop_recorder_sort", matcher: FpMatch::TokenAll(&["sort", "join", ","]), int_val: None },
    ProbeDef { name: "css_transition", matcher: FpMatch::TokenAll(&["s", "transition"]), int_val: None },
    ProbeDef { name: "intl_date_time_format", matcher: FpMatch::Token("DateTimeFormat"), int_val: None },
    ProbeDef { name: "css_set", matcher: FpMatch::TokenAll(&["s", "set"]), int_val: None },
    ProbeDef { name: "animation_end_time", matcher: FpMatch::TokenAll(&["animate", "effect", "endTime"]), int_val: None },
    ProbeDef { name: "document_visibility_state", matcher: FpMatch::TokenAll(&["document", "visibilityState"]), int_val: None },
    ProbeDef { name: "iframe_navigator_webdriver", matcher: FpMatch::TokenAll(&["navigator", "webdriver"]), int_val: None },
    ProbeDef { name: "used_js_heap_size", matcher: FpMatch::TokenAll(&["performance", "memory", "usedJSHeapSize"]), int_val: None },
    ProbeDef { name: "visual_viewport_offset_top", matcher: FpMatch::TokenAll(&["visualViewport", "offsetTop"]), int_val: None },
    ProbeDef { name: "patched_err_string_err_stack", matcher: FpMatch::Token("patchedErrStringErrStack"), int_val: None },
    ProbeDef { name: "media_resolution", matcher: FpMatch::Token("resolution"), int_val: None },
    ProbeDef { name: "media_width", matcher: FpMatch::Token("width"), int_val: Some(8000) },
    ProbeDef { name: "inverted_colors", matcher: FpMatch::Token("inverted-colors"), int_val: None },
    ProbeDef { name: "media_update", matcher: FpMatch::Token("update"), int_val: None },
    ProbeDef { name: "video_webm_vorbis", matcher: FpMatch::Token("video/webm; codecs=vorbis"), int_val: None },
    ProbeDef { name: "audio_wave_codec1", matcher: FpMatch::Token("audio/wave; codecs=1"), int_val: None },
    ProbeDef { name: "audio_wave_codec2", matcher: FpMatch::Token("audio/wave; codecs=2"), int_val: None },
    ProbeDef { name: "prop_recorder_new_function", matcher: FpMatch::TokenAll(&["Function", "apply"]), int_val: None },
    ProbeDef { name: "prop_recorder_call", matcher: FpMatch::TokenAll(&["Function", "call"]), int_val: None },
    ProbeDef { name: "prop_recorder_bind", matcher: FpMatch::TokenAll(&["Function", "bind"]), int_val: None },
    ProbeDef { name: "prop_recorder_error", matcher: FpMatch::TokenAll(&["Error", "toString", "join"]), int_val: None },
    ProbeDef { name: "audio_aac", matcher: FpMatch::Token("audio/aac;"), int_val: None },
    ProbeDef { name: "css_flood", matcher: FpMatch::TokenAll(&["s", "flood"]), int_val: None },
    ProbeDef { name: "device_height", matcher: FpMatch::Token("device-height"), int_val: None },
    ProbeDef { name: "css_box", matcher: FpMatch::TokenAll(&["s", "box"]), int_val: None },
    ProbeDef { name: "css_flex", matcher: FpMatch::TokenAll(&["s", "flex"]), int_val: None },
    ProbeDef { name: "video_mp4_bogus", matcher: FpMatch::Token("video/mp4; codecs=bogus"), int_val: None },
    ProbeDef { name: "video_ogg_theora_speex", matcher: FpMatch::Token("video/ogg; codecs=\"theora, speex\""), int_val: None },
    ProbeDef { name: "css_marker", matcher: FpMatch::TokenAll(&["s", "marker"]), int_val: None },
    ProbeDef { name: "performance_event_counts", matcher: FpMatch::Token("eventCounts"), int_val: None },
    ProbeDef { name: "gl_aliased_point_size_range", matcher: FpMatch::Token("ALIASED_POINT_SIZE_RANGE"), int_val: None },
    ProbeDef { name: "ancestor_origins", matcher: FpMatch::Token("ancestorOrigins"), int_val: None },
    ProbeDef { name: "body_check_visibility", matcher: FpMatch::Token("checkVisibility"), int_val: None },
    ProbeDef { name: "gl_aliased_line_width_range", matcher: FpMatch::Token("ALIASED_LINE_WIDTH_RANGE"), int_val: None },
    ProbeDef { name: "css_text", matcher: FpMatch::TokenAll(&["s", "text"]), int_val: None },
    ProbeDef { name: "audio_mpeg", matcher: FpMatch::Token("audio/mpeg;"), int_val: None },
    ProbeDef { name: "media_scripting", matcher: FpMatch::Token("scripting"), int_val: None },
    ProbeDef { name: "css_justify", matcher: FpMatch::TokenAll(&["s", "justify"]), int_val: None },
    ProbeDef { name: "css_place", matcher: FpMatch::TokenAll(&["s", "place"]), int_val: None },
    ProbeDef { name: "media_height", matcher: FpMatch::Token("height"), int_val: Some(8000) },
    ProbeDef { name: "prop_recorder_input_event", matcher: FpMatch::Token("InputEvent"), int_val: None },
    ProbeDef { name: "prop_recorder_proxy", matcher: FpMatch::Token("Proxy"), int_val: None },
    ProbeDef { name: "video_mp4_avc1_42c00d", matcher: FpMatch::Token("video/mp4; codecs=\"avc1.42c00d\""), int_val: None },
    ProbeDef { name: "video_webm_vorbis_vp9", matcher: FpMatch::Token("video/webm; codecs=\"vorbis,vp9\""), int_val: None },
    ProbeDef { name: "display_mode", matcher: FpMatch::Token("window-controls-overlay"), int_val: None },
    ProbeDef { name: "prop_recorder_error_constructor", matcher: FpMatch::TokenAll(&["Error", "constructor"]), int_val: None },
    ProbeDef { name: "document_create_element", matcher: FpMatch::Token("document.createElement"), int_val: None },
    ProbeDef { name: "prop_recorder_string", matcher: FpMatch::TokenAll(&["String", "join"]), int_val: None },
    ProbeDef { name: "patched_err_string_err_msg", matcher: FpMatch::Token("patchedErrStringErrMsg"), int_val: None },
    ProbeDef { name: "visibility_state_entries", matcher: FpMatch::Token("visibility-state"), int_val: None },
    ProbeDef { name: "css_css", matcher: FpMatch::TokenAll(&["s", "css"]), int_val: None },
    ProbeDef { name: "css_list", matcher: FpMatch::TokenAll(&["s", "list"]), int_val: None },
    ProbeDef { name: "css_line", matcher: FpMatch::TokenAll(&["s", "line"]), int_val: None },
    ProbeDef { name: "css_image", matcher: FpMatch::TokenAll(&["s", "image"]), int_val: None },
    ProbeDef { name: "prefers_contrast", matcher: FpMatch::Token("prefers-contrast"), int_val: None },
    ProbeDef { name: "user_activation_has_been_active", matcher: FpMatch::Token("hasBeenActive"), int_val: None },
    ProbeDef { name: "math_random_uint16", matcher: FpMatch::Token("Uint16Array"), int_val: Some(98304) },
    ProbeDef { name: "console_log_trap", matcher: FpMatch::TokenAll(&["defineProperty", "stack", "message", "log"]), int_val: None },
    ProbeDef { name: "audio_mp4_mp4a40", matcher: FpMatch::Token("audio/mp4; codecs=\"mp4a.40.2\""), int_val: None },
    ProbeDef { name: "prefers_reduced_motion", matcher: FpMatch::Token("prefers-reduced-motion"), int_val: None },
    ProbeDef { name: "crypto_random_pow", matcher: FpMatch::TokenAll(&["crypto", "getRandomValues", "Uint16Array", "pow"]), int_val: None },
    ProbeDef { name: "video_mp4_mp4v20_mp4a40", matcher: FpMatch::Token("video/mp4; codecs=\"mp4v.20.8, mp4a.40.2\""), int_val: None },
    ProbeDef { name: "css_transform", matcher: FpMatch::TokenAll(&["s", "transform"]), int_val: None },
    ProbeDef { name: "device_aspect_ratio", matcher: FpMatch::Token("device-aspect-ratio"), int_val: None },
    ProbeDef { name: "css_background", matcher: FpMatch::TokenAll(&["s", "background"]), int_val: None },
    ProbeDef { name: "video_dynamic_range", matcher: FpMatch::Token("video-dynamic-range"), int_val: None },
    ProbeDef { name: "css_ms", matcher: FpMatch::TokenAll(&["s", "ms"]), int_val: None },
    ProbeDef { name: "css_inset", matcher: FpMatch::TokenAll(&["s", "inset"]), int_val: None },
    ProbeDef { name: "prefers_reduced_transparency", matcher: FpMatch::Token("prefers-reduced-transparency"), int_val: None },
    ProbeDef { name: "forced_colors", matcher: FpMatch::Token("forced-colors"), int_val: None },
    ProbeDef { name: "date_modulo_1000", matcher: FpMatch::FreqMax(&[("Date", 1), ("now", 1), ("floor", 1)], 5), int_val: Some(1000) },
    ProbeDef { name: "video_mp2t_avc1_mp4a", matcher: FpMatch::Token("video/mp2t; codecs=\"avc1.42E01E,mp4a.40.2\""), int_val: None },
    ProbeDef { name: "prop_recorder_object", matcher: FpMatch::TokenAll(&["Object", "join"]), int_val: None },
    ProbeDef { name: "css_max", matcher: FpMatch::TokenAll(&["s", "max"]), int_val: None },
    ProbeDef { name: "prop_recorder_blob", matcher: FpMatch::Token("Blob"), int_val: None },
    ProbeDef { name: "css_align", matcher: FpMatch::TokenAll(&["s", "align"]), int_val: None },
    ProbeDef { name: "css_margin", matcher: FpMatch::TokenAll(&["s", "margin"]), int_val: None },
    ProbeDef { name: "prop_recorder_empty_func", matcher: FpMatch::TokenAll(&["toString", "join", ","]), int_val: None },
    ProbeDef { name: "css_page", matcher: FpMatch::TokenAll(&["s", "page"]), int_val: None },
    ProbeDef { name: "audio_wav_codec1_str", matcher: FpMatch::Token("audio/wav; codecs=\"1\""), int_val: None },
    ProbeDef { name: "patched_func_string_err_stack", matcher: FpMatch::Token("patchedFuncStringErrStack"), int_val: None },
    ProbeDef { name: "permissions_query", matcher: FpMatch::Token("Permissions.prototype.query"), int_val: None },
    ProbeDef { name: "audio_x_m4a", matcher: FpMatch::Token("audio/x-m4a;"), int_val: None },
    ProbeDef { name: "any_hover", matcher: FpMatch::Token("any-hover"), int_val: None },
    ProbeDef { name: "css_fill", matcher: FpMatch::TokenAll(&["s", "fill"]), int_val: None },
    ProbeDef { name: "intl_number_format", matcher: FpMatch::Token("trailingZeroDisplay"), int_val: None },
    ProbeDef { name: "css_overscroll", matcher: FpMatch::TokenAll(&["s", "overscroll"]), int_val: None },
    ProbeDef { name: "css_unicode", matcher: FpMatch::TokenAll(&["s", "unicode"]), int_val: None },
    ProbeDef { name: "location_href_guid", matcher: FpMatch::TokenAll(&["[guid]", "replaceAll"]), int_val: None },
    ProbeDef { name: "document_stylesheets_length", matcher: FpMatch::Token("styleSheets"), int_val: None },
    ProbeDef { name: "css_animation", matcher: FpMatch::TokenAll(&["s", "animation"]), int_val: None },
    ProbeDef { name: "video_mp4_avc1", matcher: FpMatch::Token("video/mp4; codecs=\"avc1.42E01E\""), int_val: None },
    ProbeDef { name: "math_random_floor_4096", matcher: FpMatch::Freq(&[("random", 1), ("Math", 2), ("floor", 1)]), int_val: Some(4096) },
    ProbeDef { name: "uuid4", matcher: FpMatch::Token("slice"), int_val: Some(256) },
    ProbeDef { name: "gl_max_fragment_uniform_vectors", matcher: FpMatch::Token("MAX_FRAGMENT_UNIFORM_VECTORS"), int_val: None },
    ProbeDef { name: "prop_recorder_fetch", matcher: FpMatch::TokenAll(&["ftp:", "catch", ","]), int_val: None },
    ProbeDef { name: "prop_recorder_promise", matcher: FpMatch::TokenAll(&["catch", "join", ","]), int_val: None },
    ProbeDef { name: "media_orientation", matcher: FpMatch::Token("orientation"), int_val: None },
    ProbeDef { name: "audio_ogg_vorbis", matcher: FpMatch::Token("audio/ogg; codecs=\"vorbis\""), int_val: None },
    ProbeDef { name: "css_offset", matcher: FpMatch::TokenAll(&["s", "offset"]), int_val: None },
    ProbeDef { name: "video_ogg_opus", matcher: FpMatch::Token("video/ogg; codecs=opus"), int_val: None },
    ProbeDef { name: "navigator_fake_ln", matcher: FpMatch::TokenAll(&["navigator", "ln"]), int_val: None },
    ProbeDef { name: "gl_unmasked_renderer", matcher: FpMatch::Token("UNMASKED_RENDERER_WEBGL"), int_val: None },
    ProbeDef { name: "parent_document_has_focus", matcher: FpMatch::FreqMax(&[("hasFocus", 1), ("parent", 1), ("document", 1)], 4), int_val: None },
    ProbeDef { name: "document_has_focus", matcher: FpMatch::FreqMax(&[("hasFocus", 1), ("document", 1)], 3), int_val: None },
    ProbeDef { name: "video_webm_vp8_vorbis", matcher: FpMatch::Token("video/webm; codecs=\"vp8, vorbis\""), int_val: None },
    ProbeDef { name: "css_font", matcher: FpMatch::TokenAll(&["s", "font"]), int_val: None },
    ProbeDef { name: "gl_max_combined_vertex_uniform_components", matcher: FpMatch::Token("MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS"), int_val: None },
    ProbeDef { name: "video_ogg_theora", matcher: FpMatch::Token("video/ogg; codecs=\"theora\""), int_val: None },
    ProbeDef { name: "overflow_inline", matcher: FpMatch::Token("overflow-inline"), int_val: None },
    ProbeDef { name: "video_3gpp_mp4v_samr", matcher: FpMatch::Token("video/3gpp; codecs=\"mp4v.20.8, samr\""), int_val: None },
    ProbeDef { name: "video_mp4", matcher: FpMatch::Token("video/mp4;"), int_val: None },
    ProbeDef { name: "gl_max_combined_fragment_uniform_components", matcher: FpMatch::Token("MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS"), int_val: None },
    ProbeDef { name: "css_perspective", matcher: FpMatch::TokenAll(&["s", "perspective"]), int_val: None },
    ProbeDef { name: "css_break", matcher: FpMatch::TokenAll(&["s", "break"]), int_val: None },
    ProbeDef { name: "video_mp4_avc1_mp4a", matcher: FpMatch::Token("video/mp4; codecs=\"avc1.64001E, mp4a.40.2\""), int_val: None },
    ProbeDef { name: "gl_unmasked_vendor", matcher: FpMatch::Token("UNMASKED_VENDOR_WEBGL"), int_val: None },
    ProbeDef { name: "css_shape", matcher: FpMatch::TokenAll(&["s", "shape"]), int_val: None },
    ProbeDef { name: "navigator_plugins", matcher: FpMatch::Token("navigator.plugins"), int_val: None },
    ProbeDef { name: "video_x_mpeg", matcher: FpMatch::Token("video/x-mpeg"), int_val: None },
];
